CREATE TABLE profiles (
    profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    experience_level VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_profiles PRIMARY KEY (profile_id),
    CONSTRAINT fk_profiles_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT uk_profiles_user UNIQUE (user_id)
);

CREATE TABLE education (
    edu_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    profile_id BIGINT NOT NULL,
    school_name VARCHAR(255) NOT NULL,
    grad_status VARCHAR(30) NOT NULL,
    degree VARCHAR(100),
    major VARCHAR(255),
    start_date DATE,
    end_date DATE,
    CONSTRAINT pk_education PRIMARY KEY (edu_id),
    CONSTRAINT fk_education_profile FOREIGN KEY (profile_id) REFERENCES profiles (profile_id) ON DELETE CASCADE
);

CREATE TABLE work_experience (
    career_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    profile_id BIGINT NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    employment_type VARCHAR(50) NOT NULL,
    position VARCHAR(255),
    start_date DATE,
    end_date DATE,
    description TEXT,
    CONSTRAINT pk_work_experience PRIMARY KEY (career_id),
    CONSTRAINT fk_work_experience_profile FOREIGN KEY (profile_id) REFERENCES profiles (profile_id) ON DELETE CASCADE
);

CREATE TABLE projects (
    project_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    profile_id BIGINT NOT NULL,
    project_name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (project_id),
    CONSTRAINT fk_projects_profile FOREIGN KEY (profile_id) REFERENCES profiles (profile_id) ON DELETE CASCADE
);

CREATE TABLE achievements (
    award_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    profile_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    issuer VARCHAR(255),
    score_or_grade VARCHAR(100),
    acquired_date DATE,
    CONSTRAINT pk_achievements PRIMARY KEY (award_id),
    CONSTRAINT fk_achievements_profile FOREIGN KEY (profile_id) REFERENCES profiles (profile_id) ON DELETE CASCADE
);
