CREATE TABLE diagnoses (
    diagnosis_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    profile_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    report_summary TEXT,
    report_content TEXT,
    error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_diagnoses PRIMARY KEY (diagnosis_id),
    CONSTRAINT fk_diagnoses_profile FOREIGN KEY (profile_id) REFERENCES profiles (profile_id)
);

CREATE TABLE jd_results (
    jd_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    diagnosis_id BIGINT NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    position VARCHAR(255),
    content TEXT NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 1,
    rank_order INTEGER,
    fit_score DECIMAL(5, 2),
    strengths_summary TEXT,
    gaps_summary TEXT,
    highlight_points TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_jd_results PRIMARY KEY (jd_id),
    CONSTRAINT fk_jd_results_diagnosis FOREIGN KEY (diagnosis_id) REFERENCES diagnoses (diagnosis_id) ON DELETE CASCADE,
    CONSTRAINT uk_jd_results_diagnosis_display_order UNIQUE (diagnosis_id, display_order),
    CONSTRAINT uk_jd_results_diagnosis_rank_order UNIQUE (diagnosis_id, rank_order)
);

CREATE TABLE chat_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    diagnosis_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    evidence_data JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_chat_messages PRIMARY KEY (message_id),
    CONSTRAINT fk_chat_messages_diagnosis FOREIGN KEY (diagnosis_id) REFERENCES diagnoses (diagnosis_id) ON DELETE CASCADE
);
